language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

deploy:
  skip_cleanup: true
  provider: npm
  email: "services@ssbinfo.com"
  api_key: "300b0d22-899a-4ad5-bab8-eca5e96569fc"
  on:
    branch: master